# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommendations_output.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 40, 91, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.grid_layout2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.grid_layout2.setContentsMargins(0, 0, 0, 0)
        self.grid_layout2.setObjectName("grid_layout2")
        self.label9 = QtWidgets.QLabel(self.layoutWidget)
        self.label9.setObjectName("label9")
        self.grid_layout2.addWidget(self.label9, 3, 0, 1, 1)
        self.label10 = QtWidgets.QLabel(self.layoutWidget)
        self.label10.setObjectName("label10")
        self.grid_layout2.addWidget(self.label10, 4, 0, 1, 1)
        self.label7 = QtWidgets.QLabel(self.layoutWidget)
        self.label7.setObjectName("label7")
        self.grid_layout2.addWidget(self.label7, 1, 0, 1, 1)
        self.label8 = QtWidgets.QLabel(self.layoutWidget)
        self.label8.setObjectName("label8")
        self.grid_layout2.addWidget(self.label8, 2, 0, 1, 1)
        self.label6 = QtWidgets.QLabel(self.layoutWidget)
        self.label6.setObjectName("label6")
        self.grid_layout2.addWidget(self.label6, 0, 0, 1, 1)
        self.header = QtWidgets.QLabel(Form)
        self.header.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.header.setObjectName("header")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(68, 40, 91, 181))
        self.widget.setObjectName("widget")
        self.grid_layout1 = QtWidgets.QGridLayout(self.widget)
        self.grid_layout1.setContentsMargins(0, 0, 0, 0)
        self.grid_layout1.setObjectName("grid_layout1")
        self.label1_2 = QtWidgets.QLabel(self.widget)
        self.label1_2.setObjectName("label1_2")
        self.grid_layout1.addWidget(self.label1_2, 0, 0, 1, 1)
        self.label2_2 = QtWidgets.QLabel(self.widget)
        self.label2_2.setObjectName("label2_2")
        self.grid_layout1.addWidget(self.label2_2, 1, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.widget)
        self.label3.setObjectName("label3")
        self.grid_layout1.addWidget(self.label3, 2, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.widget)
        self.label4.setObjectName("label4")
        self.grid_layout1.addWidget(self.label4, 3, 0, 1, 1)
        self.label5 = QtWidgets.QLabel(self.widget)
        self.label5.setObjectName("label5")
        self.grid_layout1.addWidget(self.label5, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label9.setText(_translate("Form", "9."))
        self.label10.setText(_translate("Form", "10."))
        self.label7.setText(_translate("Form", "7."))
        self.label8.setText(_translate("Form", "8."))
        self.label6.setText(_translate("Form", "6."))
        self.header.setText(_translate("Form", "Here\'s your recommendations!"))
        self.label1_2.setText(_translate("Form", "1. "))
        self.label2_2.setText(_translate("Form", "2."))
        self.label3.setText(_translate("Form", "3."))
        self.label4.setText(_translate("Form", "4."))
        self.label5.setText(_translate("Form", "5."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
